inherit_from:
  - .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  # Exclude anything that isn't really part of our code.
  # rails_helper is excluded because it's full of solecisms, but it's mostly
  # generated code and copy-and-pasted snipets from READMEs.
  Exclude:
    - 'Guardfile'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - '**/*.gemspec'
    - '**/Rakefile'
    - '**/Vagrantfile'
    - 'spec/rails_helper.rb'
    - 'lib/tasks/cucumber.rake'
    - 'features/support/env.rb'
    - 'spec/support/page_objects/**/*'
    - 'script/cucumber'
    - 'lib/log_stuff.rb'
    - 'config/routes.rb'
    - 'Gemfile'

# Layouts
# Allow long lines in specs, as it's almost impossible to fit RSpec's
# expectations into 80 characters.
Layout/LineLength:
  Max: 120
  Exclude:
    - 'features/**/*'
    - 'spec/**/*'
    - 'Gemfile'
    - 'config/initializers/devise.rb'
    - 'app/services/et_api_handler.rb'
    - 'app/forms/*'
Layout/TrailingEmptyLines:
  Enabled: true
# private/protected/public
Layout/AccessModifierIndentation:
  EnforcedStyle: indent
# Just indent parameters by two spaces. It's less volatile if methods change,
# and there's less busy work lining things up.
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
# Chain methods with trailing dots.
Layout/DotPosition:
  EnforcedStyle: trailing
# Prefer blank line after class/module start.
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Layout/LineEndStringConcatenationIndentation:
  Enabled: true
Layout/SpaceBeforeBrackets:
  Enabled: true
Layout/LineContinuationLeadingSpace:
  Enabled: true
Layout/LineContinuationSpacing:
  Enabled: true

# Metrics
Metrics/ModuleLength:
  Max: 120
  Exclude:
    - 'spec/support/helpers/**/*'
Metrics/AbcSize:
  Exclude:
    - 'spec/**/*'
    - 'app/services/et_api_handler.rb'
# Don't worry about long methods in specs.
Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'
    - 'app/models/ability.rb'
    - 'config/initializers/markdown_handler.rb'
    - 'app/services/et_api_handler.rb'
Metrics/ClassLength:
  Exclude:
    - 'app/services/et_api_handler.rb'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
    - 'lib/tasks/**/*'
Metrics/CollectionLiteralLength:
  Enabled: true

# Styles
# Allow expect {}.to blocks in specs
# but not in the code
Style/BlockDelimiters:
  Enabled: true
  Exclude:
    - 'spec/**/*'
Style/AsciiComments:
  Enabled: true
  Exclude:
    - 'spec/**/*'
Style/ClassAndModuleChildren:
  EnforcedStyle: nested
Style/CollectionMethods:
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    each_with_object: 'inject'
    inject: 'inject'
    reduce: 'inject'
    detect: 'find'
    find_all: 'select'
# No, we don't prefer each_with_object
Style/EachWithObject:
  Enabled: false
# We have a mixture at the moment, so don't enforce anything.
Style/FormatString:
  Enabled: false
# It's not really clearer to replace every if with a return if.
Style/GuardClause:
  Enabled: false
# Groups of three is not always the right thing for numeric literals
Style/NumericLiterals:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
# Percent-formatting and hash interpolation both have their place. Don't
# enforce any particular one.
Style/StringLiterals:
  Enabled: false
# I'm happy with raise, thanks.
Style/SignalException:
  Enabled: false
# Let us use foo? methods
Style/TrivialAccessors:
  AllowPredicates: true
Style/MixinUsage:
  Enabled: true
  Exclude:
    - 'spec/**/*'
    - 'features/**/*'
# Prefer sensible naming to comments everywhere.
Style/Documentation:
  Description: Document classes and non-namespace modules.
  Enabled: false
# Would enforce do_y if x over if x / do y / end. As with GuardClause above,
# this enforces code organisation that doesn't necesarily make things clearer.
Style/IfUnlessModifier:
  Enabled: false
# Just a preference to use %w[] over %w()
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '[]'
    '%W': '[]'
    '%i': '[]'
# %w doesn't always make for clearer test data
Style/WordArray:
  EnforcedStyle: brackets
Style/SymbolArray:
  EnforcedStyle: brackets
Style/NumericPredicate:
  Exclude:
    - 'spec/**/*'
Style/StringChars:
  Enabled: true
Style/SuperArguments:
  Enabled: true
Style/SuperWithArgsParentheses:
  Enabled: true
Style/SwapValues:
  Enabled: true
Style/YAMLFileRead:
  Enabled: true
RSpec/VerifiedDoubleReference:
  Enabled: true
Style/RedundantStringEscape:
  Enabled: true
Style/ReturnNilInPredicateMethodDefinition:
  Enabled: true
Style/SafeNavigationChainLength:
  Enabled: true
Style/SelectByRegexp:
  Enabled: true
Style/SendWithLiteralMethodName:
  Enabled: true
Style/SingleLineDoEndBlock:
  Enabled: true
Style/RedundantInitialize:
  Enabled: true
Style/RedundantInterpolationUnfreeze:
  Enabled: true
Style/RedundantLineContinuation:
  Enabled: true
Style/RedundantRegexpArgument:
  Enabled: true
Style/RedundantRegexpConstructor:
  Enabled: true
Style/RedundantSelfAssignmentBranch:
  Enabled: true
Style/RedundantConstantBase:
  Enabled: true
Style/RedundantCurrentDirectoryInPath:
  Enabled: true
Style/RedundantDoubleSplatHashBraces:
  Enabled: true
Style/RedundantEach:
  Enabled: true
Style/RedundantFilterChain:
  Enabled: true
Style/RedundantHeredocDelimiterQuotes:
  Enabled: true
Style/ObjectThen:
  Enabled: true
Style/OpenStructUse:
  Enabled: false
Style/OperatorMethodCall:
  Enabled: true
Style/QuotedSymbols:
  Enabled: true
Style/RedundantArgument:
  Enabled: true
Style/RedundantArrayConstructor:
  Enabled: true
Style/MultilineInPatternThen:
  Enabled: true
Style/NegatedIfElseCondition:
  Enabled: true
Style/NestedFileDirname:
  Enabled: true
Style/NilLambda:
  Enabled: true
Style/NumberedParameters:
  Enabled: true
Style/NumberedParametersLimit:
  Enabled: true
Style/MagicCommentFormat:
  Enabled: true
Style/MapCompactWithConditionalBlock:
  Enabled: true
Style/MapIntoArray:
  Enabled: true
Style/MapToHash:
  Enabled: true
Style/MapToSet:
  Enabled: true
Style/MinMaxComparison:
  Enabled: true
Style/FileWrite:
  Enabled: true
Style/HashConversion:
  Enabled: true
Style/HashExcept:
  Enabled: true
Style/IfWithBooleanLiteralBranches:
  Enabled: true
Style/InPatternThen:
  Enabled: true
Style/KeywordArgumentsMerging:
  Enabled: true
Style/ExactRegexpMatch:
  Enabled: true
Style/FetchEnvVar:
  Enabled: true
Style/FileEmpty:
  Enabled: true
Style/FileNull:
  Enabled: true
Style/FileRead:
  Enabled: true
Style/FileTouch:
  Enabled: true
Style/DigChain:
  Enabled: true
Style/DirEmpty:
  Enabled: true
Style/DocumentDynamicEvalDefinition:
  Enabled: true
Style/EmptyHeredoc:
  Enabled: true
Style/EndlessMethod:
  Enabled: true
Style/EnvHome:
  Enabled: true
Style/BitwisePredicate:
  Enabled: true
Style/CollectionCompact:
  Enabled: true
Style/CombinableDefined:
  Enabled: true
Style/ComparableClamp:
  Enabled: true
Style/ConcatArrayLiterals:
  Enabled: true
Style/DataInheritance:
  Enabled: true
Style/AmbiguousEndlessMethodDefinition:
  Enabled: true
Style/ArgumentsForwarding:
  Enabled: true
Style/ArrayIntersect:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: false
Style/PreferredHashMethods:
  Enabled: false
Style/SoleNestedConditional:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false

# RSpec
# No need to check for describe class param in support files.
RSpec/DescribeClass:
  Exclude:
    - spec/support/**/*
    - spec/views/**/*
RSpec/NestedGroups:
  Max: 10
RSpec/ExpectActual:
  Exclude:
    - 'spec/routing/**/*'
RSpec/MultipleExpectations:
  Exclude:
    - 'spec/features/**/*'
RSpec/ExampleLength:
  Exclude:
    - 'spec/**/*'
RSpec/VoidExpect:
  Enabled: false
RSpec/LeakyConstantDeclaration:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/RepeatedExampleGroupBody:
  Enabled: false
RSpec/ScatteredSetup:
  Enabled: false
RSpec/NoExpectationExample:
  Enabled: false
RSpec/InstanceVariable:
  Enabled: false

# Rails
Rails/FilePath:
  Exclude:
    - spec/routing/**/*
# ---------------
# HttpPositionalArguments is rails 5 only
# https://github.com/bbatsov/rubocop/issues/3629
# ---------------
Rails/HttpPositionalArguments:
  Enabled: false
Rails/WhereNotWithMultipleConditions:
  Enabled: true
Rails/WhereRange:
  Enabled: true
Rails/TransactionExitStatement:
  Enabled: true
Rails/UnusedRenderContent:
  Enabled: true
Rails/WhereEquals:
  Enabled: true
Rails/WhereExists:
  Enabled: true
Rails/WhereMissing:
  Enabled: true
Rails/WhereNot:
  Enabled: true
Rails/StripHeredoc:
  Enabled: true
Rails/ThreeStateBooleanColumn:
  Enabled: true
Rails/TimeZoneAssignment:
  Enabled: true
Rails/ToFormattedS:
  Enabled: true
Rails/ToSWithArgument:
  Enabled: true
Rails/TopLevelHashWithIndifferentAccess:
  Enabled: true
Rails/RootJoinChain:
  Enabled: true
Rails/RootPathnameMethods:
  Enabled: true
Rails/RootPublicPath:
  Enabled: true
Rails/SelectMap:
  Enabled: true
Rails/ShortI18n:
  Enabled: true
Rails/SquishedSQLHeredocs:
  Enabled: true
Rails/RedundantActiveRecordAllMethod:
  Enabled: true
Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: true
Rails/RedundantTravelBack:
  Enabled: true
Rails/RenderInline:
  Enabled: true
Rails/RenderPlainText:
  Enabled: true
Rails/ResponseParsedBody:
  Enabled: true
Rails/MailerName:
  Enabled: true
Rails/MatchRoute:
  Enabled: true
Rails/MigrationClassName:
  Enabled: true
Rails/NegateInclude:
  Enabled: true
Rails/Pluck:
  Enabled: true
Rails/PluckInWhere:
  Enabled: true
Rails/FreezeTime:
  Enabled: true
Rails/I18nLazyLookup:
  Enabled: true
Rails/I18nLocaleAssignment:
  Enabled: true
Rails/I18nLocaleTexts:
  Enabled: true
Rails/IgnoredColumnsAssignment:
  Enabled: true
Rails/Inquiry:
  Enabled: true
Rails/DurationArithmetic:
  Enabled: true
Rails/EagerEvaluationLogMessage:
  Enabled: true
Rails/EnumSyntax:
  Enabled: true
Rails/EnvLocal:
  Enabled: true
Rails/ExpandedDateRange:
  Enabled: true
Rails/FindById:
  Enabled: true
Rails/CompactBlank:
  Enabled: true
Rails/DangerousColumnNames:
  Enabled: true
Rails/DeprecatedActiveModelErrorsMethods:
  Enabled: true
Rails/DotSeparatedKeys:
  Enabled: true
Rails/DuplicateAssociation:
  Enabled: true
Rails/DuplicateScope:
  Enabled: true
Rails/ActionOrder:
  Enabled: true
Rails/ActiveRecordCallbacksOrder:
  Enabled: true
Rails/ActiveSupportOnLoad:
  Enabled: true
Rails/AddColumnIndex:
  Enabled: true
Rails/AfterCommitOverride:
  Enabled: true
Rails/AttributeDefaultBlockValue:
  Enabled: true
Rails/ActionControllerFlashBeforeRender:
  Enabled: true
Rails/ActionControllerTestCase:
  Enabled: true
Rails/Delegate:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/HelperInstanceVariable:
  Enabled: false
Rails/ApplicationController:
  Enabled: false

# Lint
# Allow safe assignment in conditions.
Lint/AssignmentInCondition:
  AllowSafeAssignment: false
Lint/UnmodifiedReduceAccumulator:
  Enabled: true
Lint/UselessDefined:
  Enabled: true
Lint/UselessNumericOperation:
  Enabled: true
Lint/UselessRescue:
  Enabled: true
Lint/UselessRuby2Keywords:
  Enabled: true
Lint/RequireRelativeSelfPath:
  Enabled: true
Lint/SymbolConversion:
  Enabled: true
Lint/ToEnumArguments:
  Enabled: true
Lint/TripleQuotes:
  Enabled: true
Lint/UnescapedBracketInRegexp:
  Enabled: true
Lint/UnexpectedBlockArity:
  Enabled: true
Lint/NumericOperationWithConstantResult:
  Enabled: true
Lint/OrAssignmentToConstant:
  Enabled: true
Lint/RedundantDirGlobSort:
  Enabled: true
Lint/RedundantRegexpQuantifiers:
  Enabled: true
Lint/RefinementImportMethods:
  Enabled: true
Lint/RequireRangeParentheses:
  Enabled: true
Lint/LambdaWithoutLiteralBlock:
  Enabled: true
Lint/LiteralAssignmentInCondition:
  Enabled: true
Lint/MixedCaseRange:
  Enabled: true
Lint/NoReturnInBeginEndBlocks:
  Enabled: true
Lint/NonAtomicFileOperation:
  Enabled: true
Lint/NumberedParameterAssignment:
  Enabled: true
Lint/EmptyBlock:
  Enabled: false
Lint/EmptyClass:
  Enabled: true
Lint/EmptyInPattern:
  Enabled: true
Lint/HashNewWithKeywordArgumentsAsDefault:
  Enabled: true
Lint/IncompatibleIoSelectWithFiberScheduler:
  Enabled: true
Lint/ItWithoutArgumentsInBlock:
  Enabled: true
Lint/DeprecatedConstants:
  Enabled: true
Lint/DuplicateBranch:
  Enabled: true
Lint/DuplicateMagicComment:
  Enabled: true
Lint/DuplicateMatchPattern:
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true
Lint/DuplicateSetElement:
  Enabled: true
Lint/AmbiguousAssignment:
  Enabled: true
Lint/AmbiguousOperatorPrecedence:
  Enabled: true
Lint/AmbiguousRange:
  Enabled: true
Lint/ConstantOverwrittenInRescue:
  Enabled: true
Lint/NonDeterministicRequireOrder:
  Enabled: false
Lint/RedundantSafeNavigation:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Lint/EmptyFile:
  Enabled: false
Lint/IneffectiveAccessModifier:
  Enabled: false
Lint/UselessAccessModifier:
  Enabled: false
Lint/ConstantDefinitionInBlock:
  Enabled: false

# Naming
Naming/PredicateName:
  Exclude:
    - 'spec/support/**/*'
Naming/BlockForwarding:
  Enabled: true
Naming/MemoizedInstanceVariableName:
  Enabled: false

# Security
Security/CompoundHash:
  Enabled: true
Security/IoMethods:
  Enabled: true

# Gemspec
Gemspec/AddRuntimeDependency:
  Enabled: true
Gemspec/DeprecatedAttributeAssignment:
  Enabled: true
Gemspec/DevelopmentDependencies:
  Enabled: true
Gemspec/RequireMFA:
  Enabled: true

# RSpecRails
RSpecRails/AvoidSetupHook:
  Enabled: true
RSpecRails/HaveHttpStatus:
  Enabled: true
RSpecRails/InferredSpecType:
  Enabled: false
RSpecRails/MinitestAssertions:
  Enabled: true
RSpecRails/NegationBeValid:
  Enabled: true
RSpecRails/TravelAround:
  Enabled: true

# FactoryBot
FactoryBot/ExcessiveCreateList:
  Enabled: true
FactoryBot/FactoryAssociationWithStrategy:
  Enabled: true
FactoryBot/FactoryNameStyle:
  Enabled: true
FactoryBot/IdSequence:
  Enabled: true
FactoryBot/RedundantFactoryOption:
  Enabled: true
FactoryBot/SyntaxMethods:
  Enabled: false
FactoryBot/AssociationStyle:
  Enabled: true
FactoryBot/ConsistentParenthesesStyle:
  Enabled: true

# Capybara
Capybara/SpecificActions:
  Enabled: true
Capybara/SpecificFinders:
  Enabled: true
Capybara/SpecificMatcher:
  Enabled: true
Capybara/RSpec/HaveSelector:
  Enabled: true
Capybara/ClickLinkOrButtonStyle:
  Enabled: true
Capybara/MatchStyle:
  Enabled: true
Capybara/NegationMatcher:
  Enabled: true
Capybara/RedundantWithinFind:
  Enabled: true

require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec_rails
