version: "3"

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        source_image: ${SOURCE_DOCKER_IMAGE}
    links:
      - db
    environment:
      DB_HOST: 'db'
      DB_USERNAME: 'postgres'
      TEST_BROWSER: 'firefox_local'
      RAILS_LOG_LEVEL: info
      TEST_LOCALE: ${TEST_LOCALE:-en}
      WAIT_HOSTS: db:5432

    volumes:
      - ./tmp/capybara:/home/app/et3/tmp/capybara
  db:
    image: postgres:9.6
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

