ARG source_image
FROM ${source_image}
ENV RAILS_ENV=test
ENV TEST_BROWSER=firefox_local
COPY --chown=app:app ./spec /home/app/et3/spec
COPY --chown=app:app ./test_common /home/app/et3/test_common
COPY --chown=app:app ./.rspec /home/app/et3/.rspec
COPY --chown=app:app ./.rspec_parallel /home/app/et3/.rspec_parallel
USER root
RUN apk add --no-cache firefox && \
    apk add --no-cache --virtual .build-tools git build-base curl-dev nodejs yarn && \
    cd /home/app/et3 && \
    su app -c "bundle install --no-cache --jobs=5 --retry=3 --without=development --with=assets production test --deployment && \
    bundle exec rails assets:precompile webdrivers:geckodriver:update" && \
    apk del .build-tools && \
    chown -R app:app /home/app/et3/vendor/bundle && \
    chown -R app:app /home/app/et3/log
## Add the wait script to the image
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait
USER app
CMD ["sh", "-c", "wait && bundle exec rake parallel:create[3] parallel:migrate[3] && bundle exec parallel_rspec -n 3 spec"]
