apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "et3.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "et3.name" . }}
    helm.sh/chart: {{ include "et3.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "et3.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "et3.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ping.json
              port: 8080
          readinessProbe:
            httpGet:
              path: /ping.json
              port: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: et3-aws-access-key-id
                  key: awsAccessKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: et3-aws-secret-key
                  key: awsSecretKey
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: et3-secret-key-base
                  key: secretKeyBase
            - name: DEVISE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: et3-devise-secret-key
                  key: deviseSecretKey
            - name: GTM_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: et3-gtm-account
                  key: gtmAccount
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: et3-db-password
                  key: dbPassword
            - name: RAVEN_DSN
              valueFrom:
                secretKeyRef:
                  name: et3-raven-dsn
                  key: ravenDsn
            {{- range $key, $value := $.Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
